# Generated by Django 4.2.18 on 2025-02-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0002_profile_project_skill_tag_delete_aboutme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='imageURL',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/'),
        ),
    ]
