# Generated by Django 4.2.18 on 2025-02-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_about_recentwork_service_remove_project_profile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About me', 'verbose_name_plural': 'About me'},
        ),
    ]
